### ISSUE TITLE
Release docker images for ARM64

### ISSUE THREAD

**Issue by odidev** [ArchiveTeam/grab-base-df#3]
Hi Team,

I am trying to use the docker image of this package in the ARM64 platform. As it is unavailable, I have successfully built the [same ]( https://hub.docker.com/repository/docker/odidev/grab-base/tags?page=1&ordering=last_updated) for ARM64 platform from the source.

ARM64 docker image: https://hub.docker.com/repository/docker/odidev/grab-base/tags?page=1&ordering=last_updated

Do you have any plans for releasing an ARM64 image?

May I know how the amd64 image is getting published on Docker hub?

**Comment by km09** [comment]
While this remains untested, please avoid running this against live projects. A proper arm64 image is being investigated (once various people have their hands on enough hardware to test with) but nothing set in stone at the moment.

**Comment by TomGlass** [comment]
https://github.com/ArchiveTeam/warrior-dockerfile/issues/56
